# schema version
openapi: 3.0.3

# docs
info:
  title: Advatens API
  description: API for Advatens
  version: 0.0.1

# tags are used to group the endpoints
tags:
  - name: orchard
    description: Manage orchards

# endpoints go here
paths:
  /orchards:
    post:
      tags:
        - orchard
      summary: Create a new orchard
      operationId: createOrchard
      security:
        - OAuth2: ['create:orchards']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrchardCreate'
      responses:
        '201':
          description: Orchard created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orchard'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

# reusable objects such as schemas, error types, request bodies
components:
  


  schemas:
    Orchard:
      type: object
      required:
        - id
        - name
        - location
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the orchard
        name:
          type: string
          description: Name of the orchard
        location:
          $ref: '#/components/schemas/Location'

    OrchardCreate:
      type: object
      required:
        - name
        - location
      properties:
        name:
          type: string
          description: Name of the orchard to be created
        location:
          $ref: '#/components/schemas/Location'

    Location:
      type: object
      required:
        - latitude
        - longitude
      properties:
        latitude:
          type: number
          format: float
          description: Latitude of the orchard location
        longitude:
          type: number
          format: float
          description: Longitude of the orchard location

    Error:
      type: object
      properties:
        code:
          type: integer
          description: Error code
        message:
          type: string
          description: Error description

  # Security Schemes Configuration
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://dev-n8txm445p13o88hr.us.auth0.com/oauth/token
          authorizationUrl: https://dev-n8txm445p13o88hr.us.auth0.com/authorize

          scopes:
            create:orchards: Create new orchards
            read:orchards: Read orchard information
            update:orchards: Update existing orchards
            delete:orchards: Delete orchards
    OpenID:
      type: openIdConnect
      openIdConnectUrl: https://dev-n8txm445p13o88hr.us.auth0.com/.well-known/openid-configuration

# Global security requirement
security:
  - OAuth2: ['create:orchards']
