// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package server

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for MetricMetricType.
const (
	MetricMetricTypeBatteryLevel MetricMetricType = "battery_level"
	MetricMetricTypeHumidity     MetricMetricType = "humidity"
	MetricMetricTypePh           MetricMetricType = "ph"
	MetricMetricTypeSoilMoisture MetricMetricType = "soil_moisture"
	MetricMetricTypeTemperature  MetricMetricType = "temperature"
)

// Defines values for GetMetricsParamsMetricType.
const (
	GetMetricsParamsMetricTypeBatteryLevel GetMetricsParamsMetricType = "battery_level"
	GetMetricsParamsMetricTypeHumidity     GetMetricsParamsMetricType = "humidity"
	GetMetricsParamsMetricTypePh           GetMetricsParamsMetricType = "ph"
	GetMetricsParamsMetricTypeSoilMoisture GetMetricsParamsMetricType = "soil_moisture"
	GetMetricsParamsMetricTypeTemperature  GetMetricsParamsMetricType = "temperature"
)

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code *int `json:"code,omitempty"`

	// Message Error description
	Message *string `json:"message,omitempty"`
}

// Metric defines model for Metric.
type Metric struct {
	// MetricType Type of metric
	MetricType MetricMetricType `json:"metric_type"`

	// StationId ID of the station that recorded the metric
	StationId openapi_types.UUID `json:"station_id"`

	// Timestamp Time when the measurement was taken
	Timestamp string `json:"timestamp"`

	// Value Measured value
	Value float32 `json:"value"`
}

// MetricMetricType Type of metric
type MetricMetricType string

// Orchard defines model for Orchard.
type Orchard struct {
	// Id Unique identifier for the orchard
	Id openapi_types.UUID `json:"id"`

	// Name Name of the orchard
	Name string `json:"name"`

	// OwnerId Clerk user ID of the orchard owner
	OwnerId string `json:"owner_id"`

	// Stations Stations belonging to this orchard
	Stations *[]Station `json:"stations,omitempty"`
}

// OrchardCreate defines model for OrchardCreate.
type OrchardCreate struct {
	// Name Name of the orchard to be created
	Name string `json:"name"`
}

// OrchardUpdate defines model for OrchardUpdate.
type OrchardUpdate struct {
	// Name Updated name of the orchard
	Name *string `json:"name,omitempty"`
}

// Station defines model for Station.
type Station struct {
	// DeviceId ChirpStack device ID linked to this station
	DeviceId string `json:"device_id"`

	// Id Unique identifier for the station
	Id openapi_types.UUID `json:"id"`

	// Name Name of the station
	Name string `json:"name"`

	// OrchardId ID of the orchard this station belongs to
	OrchardId openapi_types.UUID `json:"orchard_id"`
}

// StationCreate defines model for StationCreate.
type StationCreate struct {
	// DeviceId ChirpStack device ID
	DeviceId string `json:"device_id"`

	// Name Name of the station
	Name string `json:"name"`

	// OrchardId ID of the orchard to add the station to
	OrchardId openapi_types.UUID `json:"orchard_id"`
}

// StationUpdate defines model for StationUpdate.
type StationUpdate struct {
	// DeviceId Updated ChirpStack device ID
	DeviceId *string `json:"device_id,omitempty"`

	// Name Updated name of the station
	Name *string `json:"name,omitempty"`
}

// GetMetricsParams defines parameters for GetMetrics.
type GetMetricsParams struct {
	// MetricType Metric type to filter by
	MetricType GetMetricsParamsMetricType `form:"metric_type" json:"metric_type"`

	// StationId Filter by station ID (optional)
	StationId openapi_types.UUID `form:"station_id" json:"station_id"`

	// StartTime Start time for query range (optional)
	StartTime *string `form:"start_time,omitempty" json:"start_time,omitempty"`

	// EndTime End time for query range (optional)
	EndTime *string `form:"end_time,omitempty" json:"end_time,omitempty"`
}

// GetMetricsParamsMetricType defines parameters for GetMetrics.
type GetMetricsParamsMetricType string

// CreateOrchardJSONRequestBody defines body for CreateOrchard for application/json ContentType.
type CreateOrchardJSONRequestBody = OrchardCreate

// UpdateOrchardJSONRequestBody defines body for UpdateOrchard for application/json ContentType.
type UpdateOrchardJSONRequestBody = OrchardUpdate

// CreateStationJSONRequestBody defines body for CreateStation for application/json ContentType.
type CreateStationJSONRequestBody = StationCreate

// UpdateStationJSONRequestBody defines body for UpdateStation for application/json ContentType.
type UpdateStationJSONRequestBody = StationUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieve metric measurements filtered by metric type
	// (GET /metrics)
	GetMetrics(c *gin.Context, params GetMetricsParams)
	// Get all orchards for the authenticated user
	// (GET /orchards)
	GetOrchards(c *gin.Context)
	// Create a new orchard
	// (POST /orchards)
	CreateOrchard(c *gin.Context)
	// Delete an orchard by ID
	// (DELETE /orchards/{orchardId})
	DeleteOrchard(c *gin.Context, orchardId openapi_types.UUID)
	// Get a single orchard by ID
	// (GET /orchards/{orchardId})
	GetOrchard(c *gin.Context, orchardId openapi_types.UUID)
	// Update orchard partially
	// (PATCH /orchards/{orchardId})
	UpdateOrchard(c *gin.Context, orchardId openapi_types.UUID)
	// Get all stations from a orchard
	// (GET /orchards/{orchardId}/stations)
	GetStationsByOrchard(c *gin.Context, orchardId openapi_types.UUID)
	// Create a new station
	// (POST /stations)
	CreateStation(c *gin.Context)
	// Delete a station by ID
	// (DELETE /stations/{stationId})
	DeleteStation(c *gin.Context, stationId openapi_types.UUID)
	// Get a single station by ID
	// (GET /stations/{stationId})
	GetStation(c *gin.Context, stationId openapi_types.UUID)
	// Update station partially
	// (PATCH /stations/{stationId})
	UpdateStation(c *gin.Context, stationId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetMetrics(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMetricsParams

	// ------------- Required query parameter "metric_type" -------------

	if paramValue := c.Query("metric_type"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument metric_type is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "metric_type", c.Request.URL.Query(), &params.MetricType)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter metric_type: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "station_id" -------------

	if paramValue := c.Query("station_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument station_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "station_id", c.Request.URL.Query(), &params.StationId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter station_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "start_time" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_time", c.Request.URL.Query(), &params.StartTime)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter start_time: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "end_time" -------------

	err = runtime.BindQueryParameter("form", true, false, "end_time", c.Request.URL.Query(), &params.EndTime)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter end_time: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMetrics(c, params)
}

// GetOrchards operation middleware
func (siw *ServerInterfaceWrapper) GetOrchards(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOrchards(c)
}

// CreateOrchard operation middleware
func (siw *ServerInterfaceWrapper) CreateOrchard(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateOrchard(c)
}

// DeleteOrchard operation middleware
func (siw *ServerInterfaceWrapper) DeleteOrchard(c *gin.Context) {

	var err error

	// ------------- Path parameter "orchardId" -------------
	var orchardId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "orchardId", c.Param("orchardId"), &orchardId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter orchardId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteOrchard(c, orchardId)
}

// GetOrchard operation middleware
func (siw *ServerInterfaceWrapper) GetOrchard(c *gin.Context) {

	var err error

	// ------------- Path parameter "orchardId" -------------
	var orchardId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "orchardId", c.Param("orchardId"), &orchardId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter orchardId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOrchard(c, orchardId)
}

// UpdateOrchard operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrchard(c *gin.Context) {

	var err error

	// ------------- Path parameter "orchardId" -------------
	var orchardId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "orchardId", c.Param("orchardId"), &orchardId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter orchardId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateOrchard(c, orchardId)
}

// GetStationsByOrchard operation middleware
func (siw *ServerInterfaceWrapper) GetStationsByOrchard(c *gin.Context) {

	var err error

	// ------------- Path parameter "orchardId" -------------
	var orchardId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "orchardId", c.Param("orchardId"), &orchardId, runtime.BindStyledParameterOptions{Explode: false, Required: false})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter orchardId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStationsByOrchard(c, orchardId)
}

// CreateStation operation middleware
func (siw *ServerInterfaceWrapper) CreateStation(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateStation(c)
}

// DeleteStation operation middleware
func (siw *ServerInterfaceWrapper) DeleteStation(c *gin.Context) {

	var err error

	// ------------- Path parameter "stationId" -------------
	var stationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "stationId", c.Param("stationId"), &stationId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter stationId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteStation(c, stationId)
}

// GetStation operation middleware
func (siw *ServerInterfaceWrapper) GetStation(c *gin.Context) {

	var err error

	// ------------- Path parameter "stationId" -------------
	var stationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "stationId", c.Param("stationId"), &stationId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter stationId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStation(c, stationId)
}

// UpdateStation operation middleware
func (siw *ServerInterfaceWrapper) UpdateStation(c *gin.Context) {

	var err error

	// ------------- Path parameter "stationId" -------------
	var stationId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "stationId", c.Param("stationId"), &stationId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter stationId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateStation(c, stationId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/metrics", wrapper.GetMetrics)
	router.GET(options.BaseURL+"/orchards", wrapper.GetOrchards)
	router.POST(options.BaseURL+"/orchards", wrapper.CreateOrchard)
	router.DELETE(options.BaseURL+"/orchards/:orchardId", wrapper.DeleteOrchard)
	router.GET(options.BaseURL+"/orchards/:orchardId", wrapper.GetOrchard)
	router.PATCH(options.BaseURL+"/orchards/:orchardId", wrapper.UpdateOrchard)
	router.GET(options.BaseURL+"/orchards/:orchardId/stations", wrapper.GetStationsByOrchard)
	router.POST(options.BaseURL+"/stations", wrapper.CreateStation)
	router.DELETE(options.BaseURL+"/stations/:stationId", wrapper.DeleteStation)
	router.GET(options.BaseURL+"/stations/:stationId", wrapper.GetStation)
	router.PATCH(options.BaseURL+"/stations/:stationId", wrapper.UpdateStation)
}

type GetMetricsRequestObject struct {
	Params GetMetricsParams
}

type GetMetricsResponseObject interface {
	VisitGetMetricsResponse(w http.ResponseWriter) error
}

type GetMetrics200JSONResponse []Metric

func (response GetMetrics200JSONResponse) VisitGetMetricsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMetrics400JSONResponse Error

func (response GetMetrics400JSONResponse) VisitGetMetricsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetMetrics401JSONResponse Error

func (response GetMetrics401JSONResponse) VisitGetMetricsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetOrchardsRequestObject struct {
}

type GetOrchardsResponseObject interface {
	VisitGetOrchardsResponse(w http.ResponseWriter) error
}

type GetOrchards200JSONResponse []Orchard

func (response GetOrchards200JSONResponse) VisitGetOrchardsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOrchards401JSONResponse Error

func (response GetOrchards401JSONResponse) VisitGetOrchardsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrchardRequestObject struct {
	Body *CreateOrchardJSONRequestBody
}

type CreateOrchardResponseObject interface {
	VisitCreateOrchardResponse(w http.ResponseWriter) error
}

type CreateOrchard201JSONResponse Orchard

func (response CreateOrchard201JSONResponse) VisitCreateOrchardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrchard400JSONResponse Error

func (response CreateOrchard400JSONResponse) VisitCreateOrchardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrchard401JSONResponse Error

func (response CreateOrchard401JSONResponse) VisitCreateOrchardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteOrchardRequestObject struct {
	OrchardId openapi_types.UUID `json:"orchardId"`
}

type DeleteOrchardResponseObject interface {
	VisitDeleteOrchardResponse(w http.ResponseWriter) error
}

type DeleteOrchard204Response struct {
}

func (response DeleteOrchard204Response) VisitDeleteOrchardResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteOrchard401JSONResponse Error

func (response DeleteOrchard401JSONResponse) VisitDeleteOrchardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteOrchard404JSONResponse Error

func (response DeleteOrchard404JSONResponse) VisitDeleteOrchardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetOrchardRequestObject struct {
	OrchardId openapi_types.UUID `json:"orchardId"`
}

type GetOrchardResponseObject interface {
	VisitGetOrchardResponse(w http.ResponseWriter) error
}

type GetOrchard200JSONResponse Orchard

func (response GetOrchard200JSONResponse) VisitGetOrchardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetOrchard401JSONResponse Error

func (response GetOrchard401JSONResponse) VisitGetOrchardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetOrchard404JSONResponse Error

func (response GetOrchard404JSONResponse) VisitGetOrchardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateOrchardRequestObject struct {
	OrchardId openapi_types.UUID `json:"orchardId"`
	Body      *UpdateOrchardJSONRequestBody
}

type UpdateOrchardResponseObject interface {
	VisitUpdateOrchardResponse(w http.ResponseWriter) error
}

type UpdateOrchard200JSONResponse Orchard

func (response UpdateOrchard200JSONResponse) VisitUpdateOrchardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateOrchard400JSONResponse Error

func (response UpdateOrchard400JSONResponse) VisitUpdateOrchardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateOrchard401JSONResponse Error

func (response UpdateOrchard401JSONResponse) VisitUpdateOrchardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateOrchard404JSONResponse Error

func (response UpdateOrchard404JSONResponse) VisitUpdateOrchardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetStationsByOrchardRequestObject struct {
	OrchardId openapi_types.UUID `json:"orchardId,omitempty"`
}

type GetStationsByOrchardResponseObject interface {
	VisitGetStationsByOrchardResponse(w http.ResponseWriter) error
}

type GetStationsByOrchard200JSONResponse []Station

func (response GetStationsByOrchard200JSONResponse) VisitGetStationsByOrchardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetStationsByOrchard401JSONResponse Error

func (response GetStationsByOrchard401JSONResponse) VisitGetStationsByOrchardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateStationRequestObject struct {
	Body *CreateStationJSONRequestBody
}

type CreateStationResponseObject interface {
	VisitCreateStationResponse(w http.ResponseWriter) error
}

type CreateStation201JSONResponse Station

func (response CreateStation201JSONResponse) VisitCreateStationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateStation400JSONResponse Error

func (response CreateStation400JSONResponse) VisitCreateStationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateStation401JSONResponse Error

func (response CreateStation401JSONResponse) VisitCreateStationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteStationRequestObject struct {
	StationId openapi_types.UUID `json:"stationId"`
}

type DeleteStationResponseObject interface {
	VisitDeleteStationResponse(w http.ResponseWriter) error
}

type DeleteStation204Response struct {
}

func (response DeleteStation204Response) VisitDeleteStationResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteStation401JSONResponse Error

func (response DeleteStation401JSONResponse) VisitDeleteStationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteStation404JSONResponse Error

func (response DeleteStation404JSONResponse) VisitDeleteStationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetStationRequestObject struct {
	StationId openapi_types.UUID `json:"stationId"`
}

type GetStationResponseObject interface {
	VisitGetStationResponse(w http.ResponseWriter) error
}

type GetStation200JSONResponse Station

func (response GetStation200JSONResponse) VisitGetStationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetStation401JSONResponse Error

func (response GetStation401JSONResponse) VisitGetStationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetStation404JSONResponse Error

func (response GetStation404JSONResponse) VisitGetStationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateStationRequestObject struct {
	StationId openapi_types.UUID `json:"stationId"`
	Body      *UpdateStationJSONRequestBody
}

type UpdateStationResponseObject interface {
	VisitUpdateStationResponse(w http.ResponseWriter) error
}

type UpdateStation200JSONResponse Station

func (response UpdateStation200JSONResponse) VisitUpdateStationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateStation400JSONResponse Error

func (response UpdateStation400JSONResponse) VisitUpdateStationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateStation401JSONResponse Error

func (response UpdateStation401JSONResponse) VisitUpdateStationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateStation404JSONResponse Error

func (response UpdateStation404JSONResponse) VisitUpdateStationResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Retrieve metric measurements filtered by metric type
	// (GET /metrics)
	GetMetrics(ctx context.Context, request GetMetricsRequestObject) (GetMetricsResponseObject, error)
	// Get all orchards for the authenticated user
	// (GET /orchards)
	GetOrchards(ctx context.Context, request GetOrchardsRequestObject) (GetOrchardsResponseObject, error)
	// Create a new orchard
	// (POST /orchards)
	CreateOrchard(ctx context.Context, request CreateOrchardRequestObject) (CreateOrchardResponseObject, error)
	// Delete an orchard by ID
	// (DELETE /orchards/{orchardId})
	DeleteOrchard(ctx context.Context, request DeleteOrchardRequestObject) (DeleteOrchardResponseObject, error)
	// Get a single orchard by ID
	// (GET /orchards/{orchardId})
	GetOrchard(ctx context.Context, request GetOrchardRequestObject) (GetOrchardResponseObject, error)
	// Update orchard partially
	// (PATCH /orchards/{orchardId})
	UpdateOrchard(ctx context.Context, request UpdateOrchardRequestObject) (UpdateOrchardResponseObject, error)
	// Get all stations from a orchard
	// (GET /orchards/{orchardId}/stations)
	GetStationsByOrchard(ctx context.Context, request GetStationsByOrchardRequestObject) (GetStationsByOrchardResponseObject, error)
	// Create a new station
	// (POST /stations)
	CreateStation(ctx context.Context, request CreateStationRequestObject) (CreateStationResponseObject, error)
	// Delete a station by ID
	// (DELETE /stations/{stationId})
	DeleteStation(ctx context.Context, request DeleteStationRequestObject) (DeleteStationResponseObject, error)
	// Get a single station by ID
	// (GET /stations/{stationId})
	GetStation(ctx context.Context, request GetStationRequestObject) (GetStationResponseObject, error)
	// Update station partially
	// (PATCH /stations/{stationId})
	UpdateStation(ctx context.Context, request UpdateStationRequestObject) (UpdateStationResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetMetrics operation middleware
func (sh *strictHandler) GetMetrics(ctx *gin.Context, params GetMetricsParams) {
	var request GetMetricsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMetrics(ctx, request.(GetMetricsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMetrics")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetMetricsResponseObject); ok {
		if err := validResponse.VisitGetMetricsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrchards operation middleware
func (sh *strictHandler) GetOrchards(ctx *gin.Context) {
	var request GetOrchardsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrchards(ctx, request.(GetOrchardsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrchards")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetOrchardsResponseObject); ok {
		if err := validResponse.VisitGetOrchardsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateOrchard operation middleware
func (sh *strictHandler) CreateOrchard(ctx *gin.Context) {
	var request CreateOrchardRequestObject

	var body CreateOrchardJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrchard(ctx, request.(CreateOrchardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrchard")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateOrchardResponseObject); ok {
		if err := validResponse.VisitCreateOrchardResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteOrchard operation middleware
func (sh *strictHandler) DeleteOrchard(ctx *gin.Context, orchardId openapi_types.UUID) {
	var request DeleteOrchardRequestObject

	request.OrchardId = orchardId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteOrchard(ctx, request.(DeleteOrchardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteOrchard")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteOrchardResponseObject); ok {
		if err := validResponse.VisitDeleteOrchardResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOrchard operation middleware
func (sh *strictHandler) GetOrchard(ctx *gin.Context, orchardId openapi_types.UUID) {
	var request GetOrchardRequestObject

	request.OrchardId = orchardId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOrchard(ctx, request.(GetOrchardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOrchard")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetOrchardResponseObject); ok {
		if err := validResponse.VisitGetOrchardResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateOrchard operation middleware
func (sh *strictHandler) UpdateOrchard(ctx *gin.Context, orchardId openapi_types.UUID) {
	var request UpdateOrchardRequestObject

	request.OrchardId = orchardId

	var body UpdateOrchardJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateOrchard(ctx, request.(UpdateOrchardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateOrchard")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateOrchardResponseObject); ok {
		if err := validResponse.VisitUpdateOrchardResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStationsByOrchard operation middleware
func (sh *strictHandler) GetStationsByOrchard(ctx *gin.Context, orchardId openapi_types.UUID) {
	var request GetStationsByOrchardRequestObject

	request.OrchardId = orchardId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetStationsByOrchard(ctx, request.(GetStationsByOrchardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStationsByOrchard")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetStationsByOrchardResponseObject); ok {
		if err := validResponse.VisitGetStationsByOrchardResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateStation operation middleware
func (sh *strictHandler) CreateStation(ctx *gin.Context) {
	var request CreateStationRequestObject

	var body CreateStationJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateStation(ctx, request.(CreateStationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateStation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateStationResponseObject); ok {
		if err := validResponse.VisitCreateStationResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteStation operation middleware
func (sh *strictHandler) DeleteStation(ctx *gin.Context, stationId openapi_types.UUID) {
	var request DeleteStationRequestObject

	request.StationId = stationId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteStation(ctx, request.(DeleteStationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteStation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteStationResponseObject); ok {
		if err := validResponse.VisitDeleteStationResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetStation operation middleware
func (sh *strictHandler) GetStation(ctx *gin.Context, stationId openapi_types.UUID) {
	var request GetStationRequestObject

	request.StationId = stationId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetStation(ctx, request.(GetStationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetStation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetStationResponseObject); ok {
		if err := validResponse.VisitGetStationResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateStation operation middleware
func (sh *strictHandler) UpdateStation(ctx *gin.Context, stationId openapi_types.UUID) {
	var request UpdateStationRequestObject

	request.StationId = stationId

	var body UpdateStationJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateStation(ctx, request.(UpdateStationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateStation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateStationResponseObject); ok {
		if err := validResponse.VisitUpdateStationResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
