// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	OAuth2Scopes = "OAuth2.Scopes"
)

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code *int `json:"code,omitempty"`

	// Message Error description
	Message *string `json:"message,omitempty"`
}

// Location defines model for Location.
type Location struct {
	// Latitude Latitude of the orchard location
	Latitude float32 `json:"latitude"`

	// Longitude Longitude of the orchard location
	Longitude float32 `json:"longitude"`
}

// Orchard defines model for Orchard.
type Orchard struct {
	// Id Unique identifier for the orchard
	Id       openapi_types.UUID `json:"id"`
	Location Location           `json:"location"`

	// Name Name of the orchard
	Name string `json:"name"`
}

// OrchardCreate defines model for OrchardCreate.
type OrchardCreate struct {
	Location Location `json:"location"`

	// Name Name of the orchard to be created
	Name string `json:"name"`
}

// CreateOrchardJSONRequestBody defines body for CreateOrchard for application/json ContentType.
type CreateOrchardJSONRequestBody = OrchardCreate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new orchard
	// (POST /orchards)
	CreateOrchard(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CreateOrchard operation middleware
func (siw *ServerInterfaceWrapper) CreateOrchard(c *gin.Context) {

	c.Set(OAuth2Scopes, []string{"create:orchards"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateOrchard(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/orchards", wrapper.CreateOrchard)
}

type CreateOrchardRequestObject struct {
	Body *CreateOrchardJSONRequestBody
}

type CreateOrchardResponseObject interface {
	VisitCreateOrchardResponse(w http.ResponseWriter) error
}

type CreateOrchard201JSONResponse Orchard

func (response CreateOrchard201JSONResponse) VisitCreateOrchardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrchard400JSONResponse Error

func (response CreateOrchard400JSONResponse) VisitCreateOrchardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateOrchard401JSONResponse Error

func (response CreateOrchard401JSONResponse) VisitCreateOrchardResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create a new orchard
	// (POST /orchards)
	CreateOrchard(ctx context.Context, request CreateOrchardRequestObject) (CreateOrchardResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CreateOrchard operation middleware
func (sh *strictHandler) CreateOrchard(ctx *gin.Context) {
	var request CreateOrchardRequestObject

	var body CreateOrchardJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateOrchard(ctx, request.(CreateOrchardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateOrchard")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateOrchardResponseObject); ok {
		if err := validResponse.VisitCreateOrchardResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
