// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertMeasurements = `-- name: InsertMeasurements :batchexec
INSERT INTO measurement (time, station_id, metric_type, value)
VALUES ($1, $2, $3, $4)
`

type InsertMeasurementsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertMeasurementsParams struct {
	Time       pgtype.Timestamptz `json:"time"`
	StationID  uuid.UUID          `json:"station_id"`
	MetricType MetricType         `json:"metric_type"`
	Value      float64            `json:"value"`
}

func (q *Queries) InsertMeasurements(ctx context.Context, arg []InsertMeasurementsParams) *InsertMeasurementsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Time,
			a.StationID,
			a.MetricType,
			a.Value,
		}
		batch.Queue(insertMeasurements, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertMeasurementsBatchResults{br, len(arg), false}
}

func (b *InsertMeasurementsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertMeasurementsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
