// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: measurement.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMeasurementsHourly = `-- name: GetMeasurementsHourly :many
SELECT bucket::timestamptz AS time, station_id, metric_type, avg_value AS value
FROM measurement_hourly
WHERE station_id = $1
  AND metric_type = $2
  AND bucket >= $3::timestamptz
  AND bucket <= $4::timestamptz
ORDER BY bucket ASC
`

type GetMeasurementsHourlyParams struct {
	StationID  uuid.UUID          `json:"station_id"`
	MetricType MetricType         `json:"metric_type"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
}

type GetMeasurementsHourlyRow struct {
	Time       pgtype.Timestamptz `json:"time"`
	StationID  uuid.UUID          `json:"station_id"`
	MetricType MetricType         `json:"metric_type"`
	Value      float64            `json:"value"`
}

func (q *Queries) GetMeasurementsHourly(ctx context.Context, arg GetMeasurementsHourlyParams) ([]GetMeasurementsHourlyRow, error) {
	rows, err := q.db.Query(ctx, getMeasurementsHourly,
		arg.StationID,
		arg.MetricType,
		arg.StartTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMeasurementsHourlyRow
	for rows.Next() {
		var i GetMeasurementsHourlyRow
		if err := rows.Scan(
			&i.Time,
			&i.StationID,
			&i.MetricType,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
