// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Orchard struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	OwnerID   string           `json:"owner_id"`
}

type Station struct {
	ID        uuid.UUID        `json:"id"`
	OrchardID uuid.UUID        `json:"orchard_id"`
	Name      string           `json:"name"`
	DeviceID  string           `json:"device_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
