// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: orchard.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOrchard = `-- name: CreateOrchard :one
INSERT INTO orchard (name, owner_id)
VALUES ($1, $2)
    RETURNING id, name, created_at, owner_id
`

type CreateOrchardParams struct {
	Name    string `json:"name"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) CreateOrchard(ctx context.Context, arg CreateOrchardParams) (Orchard, error) {
	row := q.db.QueryRow(ctx, createOrchard, arg.Name, arg.OwnerID)
	var i Orchard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.OwnerID,
	)
	return i, err
}

const deleteOrchard = `-- name: DeleteOrchard :exec
DELETE FROM orchard
WHERE id = $1
`

func (q *Queries) DeleteOrchard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrchard, id)
	return err
}

const getOrchardById = `-- name: GetOrchardById :one
SELECT id, name, created_at, owner_id FROM orchard
WHERE id = $1
`

func (q *Queries) GetOrchardById(ctx context.Context, id uuid.UUID) (Orchard, error) {
	row := q.db.QueryRow(ctx, getOrchardById, id)
	var i Orchard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.OwnerID,
	)
	return i, err
}

const listOrchards = `-- name: ListOrchards :many
SELECT id, name, created_at, owner_id FROM orchard
         WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrchards(ctx context.Context, ownerID string) ([]Orchard, error) {
	rows, err := q.db.Query(ctx, listOrchards, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Orchard
	for rows.Next() {
		var i Orchard
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrchard = `-- name: UpdateOrchard :one
UPDATE orchard
SET name = coalesce($2, name)
WHERE id = $1
    RETURNING id, name, created_at, owner_id
`

type UpdateOrchardParams struct {
	ID   uuid.UUID `json:"id"`
	Name *string   `json:"name"`
}

func (q *Queries) UpdateOrchard(ctx context.Context, arg UpdateOrchardParams) (Orchard, error) {
	row := q.db.QueryRow(ctx, updateOrchard, arg.ID, arg.Name)
	var i Orchard
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.OwnerID,
	)
	return i, err
}
