// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrchard(ctx context.Context, arg CreateOrchardParams) (Orchard, error)
	CreateStation(ctx context.Context, arg CreateStationParams) (Station, error)
	DeleteOrchard(ctx context.Context, id uuid.UUID) error
	DeleteStation(ctx context.Context, id uuid.UUID) error
	GetOrchardById(ctx context.Context, id uuid.UUID) (Orchard, error)
	GetStationById(ctx context.Context, id uuid.UUID) (Station, error)
	ListOrchards(ctx context.Context, ownerID string) ([]Orchard, error)
	ListOrchardsWithStations(ctx context.Context, ownerID string) ([]ListOrchardsWithStationsRow, error)
	ListStationsByOrchard(ctx context.Context, orchardID uuid.UUID) ([]Station, error)
	UpdateOrchard(ctx context.Context, arg UpdateOrchardParams) (Orchard, error)
	UpdateStation(ctx context.Context, arg UpdateStationParams) (Station, error)
}

var _ Querier = (*Queries)(nil)
