// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: station.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createStation = `-- name: CreateStation :one
INSERT INTO station (name, device_id, orchard_id)
VALUES ($1, $2, $3)
    RETURNING id, orchard_id, name, device_id, created_at
`

type CreateStationParams struct {
	Name      string    `json:"name"`
	DeviceID  string    `json:"device_id"`
	OrchardID uuid.UUID `json:"orchard_id"`
}

func (q *Queries) CreateStation(ctx context.Context, arg CreateStationParams) (Station, error) {
	row := q.db.QueryRow(ctx, createStation, arg.Name, arg.DeviceID, arg.OrchardID)
	var i Station
	err := row.Scan(
		&i.ID,
		&i.OrchardID,
		&i.Name,
		&i.DeviceID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStation = `-- name: DeleteStation :exec
DELETE FROM station
WHERE id = $1
`

func (q *Queries) DeleteStation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStation, id)
	return err
}

const getStationById = `-- name: GetStationById :one
SELECT id, orchard_id, name, device_id, created_at FROM station
WHERE id = $1
`

func (q *Queries) GetStationById(ctx context.Context, id uuid.UUID) (Station, error) {
	row := q.db.QueryRow(ctx, getStationById, id)
	var i Station
	err := row.Scan(
		&i.ID,
		&i.OrchardID,
		&i.Name,
		&i.DeviceID,
		&i.CreatedAt,
	)
	return i, err
}

const listStationsByOrchard = `-- name: ListStationsByOrchard :many
SELECT id, orchard_id, name, device_id, created_at FROM station
WHERE orchard_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListStationsByOrchard(ctx context.Context, orchardID uuid.UUID) ([]Station, error) {
	rows, err := q.db.Query(ctx, listStationsByOrchard, orchardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Station
	for rows.Next() {
		var i Station
		if err := rows.Scan(
			&i.ID,
			&i.OrchardID,
			&i.Name,
			&i.DeviceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStation = `-- name: UpdateStation :one
UPDATE station
SET name = coalesce($2, name)
WHERE id = $1
    RETURNING id, orchard_id, name, device_id, created_at
`

type UpdateStationParams struct {
	ID   uuid.UUID `json:"id"`
	Name *string   `json:"name"`
}

func (q *Queries) UpdateStation(ctx context.Context, arg UpdateStationParams) (Station, error) {
	row := q.db.QueryRow(ctx, updateStation, arg.ID, arg.Name)
	var i Station
	err := row.Scan(
		&i.ID,
		&i.OrchardID,
		&i.Name,
		&i.DeviceID,
		&i.CreatedAt,
	)
	return i, err
}
